/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;
import java.io.IOException;
import java.util.*;

import org.example.app.entities.Train;
import org.example.app.entities.User;
import org.example.app.service.userBookingService;
import org.example.app.util.UserServiceUtil;
import org.example.list.LinkedList;

import static org.example.utilities.StringUtils.join;
import static org.example.utilities.StringUtils.split;
import static org.example.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner sc=new Scanner(System.in);
        int option=0;
        userBookingService userbookingservice;
        try{
              userbookingservice=new userBookingService();
        }catch(IOException ex){
            System.out.println("There is something wrong");
            return;
        }
        while(option!=7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option=sc.nextInt();
            Train trainSelected=new Train();
            switch(option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = sc.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = sc.next();
                    User userToSignup = new User(nameToSignUp, passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp), new ArrayList<>(), UUID.randomUUID().toString());
                    userbookingservice.signUp(userToSignup);
                    break;
                case 2:
                    System.out.println("Enter the username to Login");
                    String nameToLogin = sc.next();
                    System.out.println("Enter the password to signup");
                    String passwordToLogin = sc.next();
                    User userToLogin = new User(nameToLogin, passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(), UUID.randomUUID().toString());
                    try{
                        userbookingservice = new userBookingService(userToLogin);
                    }catch (IOException ex){
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your bookings");
                    userbookingservice.fetchBooking();
                    break;
                case 4:
                    System.out.println("Type your source station");
                    String source = sc.next();
                    System.out.println("Type your destination station");
                    String dest = sc.next();
                    List<Train> trains = userBookingService.getTrains(source, dest);
                    int index = 1;
                    for (Train t: trains){
                        System.out.println(index+" Train id : "+t.getTrainId());
                        for (Map.Entry<String, String> entry: t.getStationTime().entrySet()){
                            System.out.println("station "+entry.getKey()+" time: "+entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                    trainSelected = trains.get(sc.nextInt());
                    break;
                case 5:
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats=userbookingservice.fetchSeats(trainSelected);
                    for(List<Integer> row:seats){
                        for(Integer val:row){
                            System.out.println(val+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("SELECT SEAT BY TYPING THE ROW AND COLUMN");
                    System.out.println("Enter The Row");
                    int row=sc.nextInt();
                    System.out.println("Enter The Column");
                    int col=sc.nextInt();
                    System.out.println("Booking your seat....");
                    Boolean booked=userbookingservice.bookseat(trainSelected,row,col);
                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Booked Enjoy Your Journey");
                    }else{
                        System.out.println("Sorry try again");
                    }
                    break;
                default:
                    break;
            }
        }
    }
}
